# Numpy
- Numpy는 Numerical Python의 줄임말로, 과학/공학 계산을 위한 수치 계산 라이브러리임.

## 1. 배열 생성

### 1.1. 리스트로부터 배열 생성

In [1]:
import numpy as np # numpy 패키지 로드하여 np로 사용

In [7]:
a = [[1,2,3], [4,5,6], [7,8,9]] # 리스트 생성
b = np.array(a) # 리스트를 numpy array로 변환
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
b.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
print(b.ndim) # 배열의 차원

2


In [10]:
print(b.shape) # 배열의 모양(행, 열)

(3, 3)


In [11]:
b[0][1]  # 배열의 원소 접근1

2

In [12]:
b[0,1]  # 배열의 원소 접근2

2

In [13]:
b[0,2]  # b[0][2]와 동일

3

In [14]:
b[2,0]  # b[2][0]와 동일 

7

### 1.2. 특수한 배열의 생성

- np.arange(scalar): 파이썬에서 사용하는 range() 함수의 결과가 요소로 들어감. range()에서 사용가능한 기법들 역시 사용가능(첫번째 숫자 지정, 두번째 숫자 지정, step size 지정)
- np.zeros(int or tuple): 0이 들어있는 배열을 간단하게 생성해주는 명령어
- np.ones(int or tuple): 1이 들어있는 배열을 간단하게 생성해주는 명령어
- np.linspace(scalar, num=n): 간격을 지정하여 선형으로 배치된 n개의 값을 갖는 배열을 만들 수 있음.

In [15]:
np.arange(10) # 0부터 9까지 1씩 증가하는 1차원 배열 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
print(np.arange(10)) # 0부터 9까지 1씩 증가하는 1차원 배열 생성

[0 1 2 3 4 5 6 7 8 9]


In [17]:
print(np.arange(5, 10)) # 5부터 9까지 1씩 증가하는 1차원 배열 생성

[5 6 7 8 9]


In [18]:
np.arange(100, step=5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [19]:
print(np.zeros((2,2))) # (2,2) 영행렬 생성

[[0. 0.]
 [0. 0.]]


In [20]:
print(np.ones((2,3))) # (2,3) 유닛행렬 생성

[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
print(np.linspace(0, 100, 3)) # 0~100 사이에 n개의 균등한 간격을 가진 데이터를 생성

# 첫번째 데이터: 0
# 마지막 데이터: 100

[  0.  50. 100.]


### 1.3. 배열의 차원 변환

In [27]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [29]:
# step = 5 --> 5씩 건너뛰면서 배열을 생성

a1 = np.arange(100, step=5)
a1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [30]:
# 4x5 2차원 행렬로 변환

b = a1.reshape((4,5))
b

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [31]:
# 2x2x5 3차원 행렬로 변환

c = a1.reshape((2,2,5))
c

array([[[ 0,  5, 10, 15, 20],
        [25, 30, 35, 40, 45]],

       [[50, 55, 60, 65, 70],
        [75, 80, 85, 90, 95]]])

In [30]:
b.ndim

2

In [31]:
a.ndim

1

In [32]:
c.ndim

3

In [ ]:
# 예제

# 0~39까지 1씩 증가하는 40개의 배열을 numpy array로 구성
# 생성된 array를 5x8 2차원 행렬로 변환
# 생성된 array를 4x2x5 3차원 행렬로 변환

## 2. Numpy 연산

### 2.1. 사칙연산

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.add(a,b) # c = a + b

c

array([5, 7, 9])

In [19]:
c = a + b
c

array([5, 7, 9])

In [20]:
d = np.multiply(a,b) # d = a*b
d

array([ 4, 10, 18])

In [21]:
d = a*b
d

array([ 4, 10, 18])

In [22]:
e = np.divide(a, b) # e = a/b
e

array([0.25, 0.4 , 0.5 ])

In [23]:
e = a/b
e

array([0.25, 0.4 , 0.5 ])

### 2.2. 행렬의 곱

In [2]:
arr1 = [[1,2], [3,4]]
arr2 = [[5,6], [7,8]]

a = np.array(arr1)

b = np.array(arr2)

c = np.dot(a,b)

print(a)
print()
print(b)
print()
print(c)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]


### 2.3. 모든 원소의 합과 곱

In [4]:
a = np.array([[1,2,3], [3,4,8]])
s = np.sum(a)
print(a)
print()
print("sum =", a.sum()) 
print("sum =", s) # s의 결과는 a.sum()의 결과와 동일

[[1 2 3]
 [3 4 8]]

sum = 21
sum = 21


In [68]:
print("sum by row=", a.sum(axis=0)) # 행방향으로 합을 구함.

sum by row= [ 4  6 11]


In [69]:
print("sum by column=", a.sum(axis=1)) # 열방향으로 합을 구함.

sum by column= [ 6 15]


In [70]:
print("product=", a.prod())

product= 576


In [71]:
print("mean=", a.mean())

mean= 3.5


In [72]:
print("standard deviation=", a.std())

standard deviation= 2.217355782608345


In [ ]:
# 예제

# a = np.array([[2,3,4], [5,6,7]])

# a.prod()
# a.prod(axis=0)
# a.prod(axis=1)

# a.mean()
# a.mean(axis=0)
# a.mean(axis=1)
